physics=int(input("Enter marks obtained in Physics:"))
chemistry=int(input("Enter marks obtained in Chemistry:"))
mathe=int(input("Enter marks obtained in Maths:"))
eng=int(input("Enter marks obtained in English:"))
ip=int(input("Enter marks obtained in IP:"))
total=(physics+chemistry+mathe+eng+ip)
percentage=(total/5)
print("Total marks:", total )
print("Percentage:", percentage)
